# Process name
name: Deploy Astro

# Branch being executed
on:
    push:
        branches:
            - master

concurrency:
     group: pages
     cancel-in-progress: true

# Permissions
permissions:
    contents: write
    pages: write
    id-token: write

# Tasks
jobs:
    # Job's name: Build
    build:
        # Virtual machine
        runs-on: ubuntu-latest
        steps:
            # Download repo
            - uses: actions/checkout@v5
            # Install node
            - uses: actions/setup-node@v5
              with:
                node-version: 22
                cache: npm
            # To determinate the version's type in commit    
            - id: bump
              run: |
                MESSAGE="${{ github.event.head_commit.message }}"
                if echo "$MESSAGE" | grep -q "#major"; then
                  echo "type=major" >> "$GITHUB_OUTPUT"
                elif echo "$MESSAGE" | grep -q "#minor"; then
                  echo "type=minor" >> "$GITHUB_OUTPUT"
                else
                  echo "type=patch" >> "$GITHUB_OUTPUT"
                fi
            # Update version in package.json
            - run: npm version ${{ steps.bump.outputs.type }} --no-git-tag-version
            # Commit of package.json with the new version
            - run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add package.json package-lock.json
                git commit -m "chore: bump version [skip ci]"
                git push
            # Install dependencies
            - run: npm ci
            # Generates build
            - run: npm run build
            # Upload web to generate artifact
            - uses: actions/upload-pages-artifact@v5
              with:
               path: ./dist
    # Deploy
    deploy:
      # what needs
      needs: build
      # virtual machine
      runs-on: ubuntu-latest
      # set environment to deploy endpoint
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        # Download artifact
        - id: deployment
          # Gets the url page
          uses: actions/deploy-pages@v5
